[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[context.dev.environment]
  NASA_API_KEY = "bbPZTSieIbxGv876Tj1ERj22p8pgnJ53feOnVwwO"

[context.production.environment]
  NASA_API_KEY = "bbPZTSieIbxGv876Tj1ERj22p8pgnJ53feOnVwwO"

[[redirects]]
  from = "/api/neo/browse"
  to = "/.netlify/functions/neo-browse"
  status = 200

[[redirects]]
  from = "/api/neo/*"
  to = "/.netlify/functions/neo-detail"
  status = 200

[[redirects]]
  from = "/api/usgs/elevation"
  to = "/.netlify/functions/usgs-elevation"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200